### ISSUE TITLE
[Toolbar] On window integration alternative

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#192]
### Discussed in https://github.com/BiGilSoft/WindowTop/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **SanshooSenshi** December 15, 2021</sup>
If there is enough space on the window ( usualy it's always the case, except for many tabs on a browser ) 
It could be a better workflow if we could have shortcuts displaying instead of waiting for the little "arrow" to show then click on it ... 

with a on " mouse over " = no transparency for each options ...
![windowTop integration](https://user-images.githubusercontent.com/85396423/146167448-26a9c309-ad1f-4ff2-bc3a-4206ace7a608.png)
 </div>

**Comment by gileli121** [comment]
Can't be done in a way that will work and look fine.
It does not worth the effort

**Comment by gileli121** [comment]
Similar to this behavior:
![image](https://user-images.githubusercontent.com/17680514/153269524-90f0970a-5f49-476e-87b6-cf061c262a3b.png)

I think that I have idea!..

If the mouse is above this button:
![image](https://user-images.githubusercontent.com/17680514/153253362-b3594188-c7f6-4989-a8d7-c0100027f64d.png)
Then after 0.5 seconds (or less?) show this:
![image](https://user-images.githubusercontent.com/17680514/153253548-5f821597-5a04-4bc3-bc40-08d3c280da3e.png)


If this mode is enabled, It will replace the arrow button

_Originally posted by @gileli121 in https://github.com/BiGilSoft/WindowTop/discussions/175#discussioncomment-2143134_

**Comment by gileli121** [comment]
I finally developed this behavior:
![toolbar_on_minimize_hover_demo1](https://user-images.githubusercontent.com/17680514/153717529-7044526b-88f3-4504-adb5-02a4ff136dc9.gif)

If there is no minimize button, it will show the regular arrow
![toolbar_on_minimize_hover_demo2](https://user-images.githubusercontent.com/17680514/153717610-5b872748-bb52-44a9-8a87-64a16aad52ff.gif)

Feel free to test:
[WindowTop 5.10.0-beta2 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8053887/WindowTop.5.10.0-beta2.-.setup.exe.zip)

This is very early stage and for now this behavior is enabled by default and can't be disabled..
It is only because it is alpha. I did not implemented yet the settings UI for controlling this behavior.

Let me know how it works

**Comment by cpasoft** [comment]
Mmmmm... It sounds promising... This should work also on Windows 10, I suppose, didn't it??
Downloading right now... I'll let you know how it works to me... (now on windows 10, monday on Windows 11)

**Comment by cpasoft** [comment]
Testing on windows 10... working without problem...
The memory leaking on the settings is still there.
I suppose the new keep away algorithm it is not present in this tree, isn't it??
By the moment, it's working great.

**Comment by cpasoft** [comment]
On telegram desktop app, it show the green arrow instead of using minimize button...
I guess this is because this app is using an  not native window... so it is not windowtop issue... Just I put it here for future references...

**Comment by gileli121** [comment]
@cpasoft 
Actually, it should work even with telegram.
I tested it.
I guess that I broke it, or maybe it is broke in Windows 10

**Comment by cpasoft** [comment]
On windows 10 is not working on MMC's windows (for example, services.msc)
I'll test this behaivior on Windows 11...

**Comment by gileli121** [comment]
@cpasoft 
What do you mean by saying "not working"? 
It works for `services.msc` 
![image](https://user-images.githubusercontent.com/17680514/153846795-3ee96df4-f04c-4bd0-8aac-3079e7f25306.png)

The only issue is that when I try to make it on top, I get this error:
![image](https://user-images.githubusercontent.com/17680514/153846877-d05052b8-c5fe-4a23-a2d0-1cfb3c86b49a.png)

But this is not real issue because the app is not running as Admin. It even telling you what the issue is

**Comment by cpasoft** [comment]
It is not working to me... It appears the green arrow on the top, not on the minimize icon...

![imagen](https://user-images.githubusercontent.com/29692062/153853077-81551035-6aa3-495e-b1f7-f45ba6aa4d27.png)

**Comment by cpasoft** [comment]
Testing on Windows 11, working perfectly... Also working the round corners...

**Comment by cpasoft** [comment]
Here a video from windows...

https://user-images.githubusercontent.com/29692062/153856940-79f683fa-b550-459f-9506-de56fecc530c.mp4

**Comment by cpasoft** [comment]
Here a video from windows 10...

https://user-images.githubusercontent.com/29692062/153856940-79f683fa-b550-459f-9506-de56fecc530c.mp4

**Comment by gileli121** [comment]
@cpasoft 
Thanks. I reproduced it.
And this feature is free also for the Demo version.

At first, it failed to detect the minimize button of this window.
But there is a fallback logic that triggered once you moved the mouse to the minimize button.
At that point, you helped the app to understand that there is minimize button there... so after that it stopped to show the arrow and worked as expected

**Comment by gileli121** [comment]
@cpasoft 
This beta contains bug fixes for cases when the DPI settings are not 100%
[WindowTop 5.10.0-beta4 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8083625/WindowTop.5.10.0-beta4.-.setup.exe.zip)

**Comment by cpasoft** [comment]
Downloading the beta4 version...
Testing right now...

**Comment by cpasoft** [comment]
Good & bad news... sorry 'bout that...

Working well on mmc.exe, but still broken on office software... 
Word, excel, onenote, ... appear the green arrow and also working on the minimize icon.
In skype we have the green arrow, but not working on the minimize icon...

I suppose it is difficult to detect what kind of window the app is using... You are doing a great job BTW.

**Comment by gileli121** [comment]
@cpasoft 
Thanks!

> but still broken on office software...

1. What office version you have installed?
2. Did you tested it on Windows 10 or 11?

**Comment by cpasoft** [comment]
Office 365, on Windows 10...
Tomorrow I'l test it on Windows 11 if you want...

**Comment by gileli121** [comment]
@cpasoft 
Thanks.
I am installing now office 365 and I will test it also.
I will do it on Windows 11.

I hope to reproduce and fix the bug on my system

**Comment by gileli121** [comment]
@cpasoft 
I tested it with office 365 on windows 11 and it worked without issues.
Maybe it is problem in Windows 10

**Comment by gileli121** [comment]
@cpasoft 
I was able to reproduce the bug on Windows 10 & office 365.
I fixed the bug in beta 5. Feel free to test:
[WindowTop 5.10.0-beta5 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8100610/WindowTop.5.10.0-beta5.-.setup.exe.zip)

Note that in this version I implemented UI for changing this behavior and it is off by default:
![image](https://user-images.githubusercontent.com/17680514/154766656-48ffc4eb-9095-4b8c-8a53-b47aa9527d19.png)
You need to enable the option this time (unlike in old betas)

In addition, now I implemented UI to save and delete window configuration directly from the toolbar
![image](https://user-images.githubusercontent.com/17680514/154766783-06c52b68-3653-4c19-a3ca-6e5e9a24366a.png)
![image](https://user-images.githubusercontent.com/17680514/154766874-bbbe027c-3ec6-4a33-823f-5c0236bb6a0b.png)


This beta is a candidate to be the next stable release.
I finished implementing all the stuff that needs to be done

**Comment by gileli121** [comment]
@cpasoft 
There was a regression in beta 5 that it detected minimize button here:
![image](https://user-images.githubusercontent.com/17680514/154790262-75743011-6e32-40cc-8460-dc427a871731.png)

Should be fixed now.
Check this please:
[WindowTop 5.10.0-beta6 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8101591/WindowTop.5.10.0-beta6.-.setup.exe.zip)

Thanks a lot!

**Comment by cpasoft** [comment]
> @cpasoft There was a regression in beta 5 that it detected minimize button here: ![image](https://user-images.githubusercontent.com/17680514/154790262-75743011-6e32-40cc-8460-dc427a871731.png)
> 
> Should be fixed now. Check this please: [WindowTop 5.10.0-beta6 - setup.exe.zip](https://github.com/BiGilSoft/WindowTop/files/8101591/WindowTop.5.10.0-beta6.-.setup.exe.zip)
> 
> Thanks a lot!

I'll test this tomorrow... I've seen beta8 on other discussion (French translation, I think). Which is the last beta version??

**Comment by gileli121** [comment]
@cpasoft 
Thanks!
Beta 7 contains the last fix from here and also the French translation.
I prefer that you will try beta 7 from the other discussion (#179).

Thanks

**Comment by cpasoft** [comment]
Testing Beta7:
On word, excel, onenote and outlook working perfect.
Still not working on Skype, 
The green arrow appear on OneDrive as well, but this is correct, because onedrive doesn't have minimize button.

The memory leaking is still there. If you play around the settings, it takes more than 2.5Gb. of memory, and then it will not be free up.
If you have a window open and you change settings, this are not applied to this open windows... you must close this app and reopen again to commit the changes to this window.

I've not seen other issues by the moment...

**Comment by gileli121** [comment]
@cpasoft 
Thanks, I will mark this issue as done.
About the memory leak issue, I opened issue #202

**Comment by gileli121** [comment]
@cpasoft 
This feature released now in v5.10.0
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.10.0
In addition, the memory leak issue also fixed/reduced a lot (#202)

If there are issues, let me know and I will reopen this issue.
Thanks

**Comment by cpasoft** [comment]
Well done, very very good work here...
Thanks @gileli121 !!!

**Comment by cpasoft** [comment]
Testing the brand new 5.10.0
@gileli121 ... I've found another app where this feature doesn't work (Windows 10 & Windows 11)
On the Windows Terminal, the minimize button is not working. It shows the green arrow. 
![imagen](https://user-images.githubusercontent.com/29692062/155125153-c3430157-e43c-410f-a08f-4e2d3c563c1c.png)

**Comment by gileli121** [comment]
@cpasoft 
I think that it is bug in Windows Terminal.
Because the OS also does not show this:
![image](https://user-images.githubusercontent.com/17680514/155215315-9845ac1c-4c40-4dc5-8bd8-d3d14a6ba812.png)
When the mouse is above the maximize button.

The app try to detect these kind of buttons in similar way as how the OS detects the maximize button.
If OS failed to detect the maximize button, it probably means that Windows Terminal does not respond to [WM_NCHITTEST](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest) message..

Windows Terminal should process [WM_NCHITTEST](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest) message and should response with `HTMAXBUTTON` (9) when the mouse is above the maximize button, and when the mouse is above the minimize button, it should response with `HTMINBUTTON` (8)

It looks like it is not the case..
The following C++ code proves it:
```c++
#include <iostream>
#include <Windows.h>


int main()
{

	while (true)
	{
		Sleep(250);
		POINT point;
		GetCursorPos(&point);
		auto hwnd = (HWND)WindowFromPoint(point);
		RECT rect;

		auto WM_NCHITTEST_res = SendMessage(hwnd, WM_NCHITTEST, NULL, MAKELPARAM(point.x, point.y));

		std::cout << "HWND: " << hwnd << ", " << "WM_NCHITTEST: " << WM_NCHITTEST_res << std::endl;

	}

	return 0;
}

```
When the mouse is above the minimize button, it print the value 2 (should print 8), and when it is above the maximize button, it prints 2 again instead of 9.. and this is why the OS failed to show this
![image](https://user-images.githubusercontent.com/17680514/155217056-84741591-90d7-4c12-abd8-004de6c6e7f6.png)
(no 9 returned)

And also why WindowTop failed to show the toolbar (no 8 returned)


So maybe you should open the bug in Windows Terminal.
You can open it there: https://github.com/microsoft/terminal/issues

**Comment by cpasoft** [comment]
Yes, It must be a bug in Windows Terminal.
Maybe I'll report that... Thanks!
